---
# tasks file
- name: rhel
  ansible.builtin.set_fact:
    mydistribution: "rhel"

- name: Install Docker
  ansible.builtin.yum:
    name:
      - docker
    state: latest
    update_cache: true

- name: Start Docker
  ansible.builtin.service:
    name: "docker"
    enabled: true
    state: started
